title: Melanie Polkosky
description: A social-cognitive psychologist from Memphis, Tennessee who designs with words.
small_description: Designing with words
twitter: melaniepolkosky
url: https://melanie-polkosky.netlify.com

collections:
  portfolio:
    output: true
    collections_dir: portfolio

permalink: pretty

email: melanie@melaniepolkosky.com
book_link: https://www.amazon.co.uk/Uncovering-Truffles-Scarcity-Value-Women/dp/1515304280/ref=sr_1_1?keywords=uncovering+truffles&qid=1585251895&sr=8-1

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

plugins:
  - jekyll-redirect-from