[[plugins]]
package = "@netlify/plugin-sitemap"

    [plugins.inputs]
    buildDir = "_site"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
package = "netlify-plugin-subfont"

    [plugins.inputs]
    inlineCss = true

[[plugins]]
package = "netlify-plugin-inline-critical-css"