# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# media_folder: 'images/'
site_url: https://melaniepolkosky.com
media_library:
  name: cloudinary
  config:
    cloud_name: mckvr
    api_key: 146799337454777
    default_transformations:
      - - quality: auto
          crop: fill
          dpr: auto


collections:
  - name: 'portfolio'
    identifier_field: thumbnail_title
    editor:
        preview: false
    label: 'Portfolio Page'
    slug: '{{slug}}'
    folder: '_portfolio/'
    create: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'portfolio-single' }
      - { label: 'Title', name: 'thumbnail_title', widget: 'string', required: true, hint: "The title for the thumbnail e.g. IBM"  }
      - { label: 'Page Title', name: 'title', widget: 'string', required: true, hint: "e.g. Metric-based funding strategy for citywide social programs."  }
      - { label: 'Category', name: 'category', widget: 'select', required: true, options: ['Strategy Consulting', 'Training', 'UI Design', 'UX Research'] }
      - { label: 'Role', name: 'role', widget: 'string', required: false, hint: "e.g. Strategy Consulting" }
      - { label: 'Company', name: 'company', widget: 'string', required: false, hint: "e.g. IBM" }
      - { label: 'Client', name: 'client', widget: 'string', required: false, hint: "e.g. Belfast City Council" }
      - { label: 'Time', name: 'time', widget: 'string', required: false, hint: "The displayed date for the case study e.g. 2020-2021" }
      - { label: 'Sorting Date', name: 'date', widget: 'datetime', hint: "The date used for sorting. Leave set to Now to display as most recent" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        hint: "Leave blank in no testimonials to display"
        fields:
          - { label: 'Full Name', name: 'name', widget: 'string', required: false, hint: "Name of the person if avail" }
          - { label: 'Job Title', name: 'title', widget: 'string', required: false, hint: "E.g. Director, Belfast City Council" }
          - { label: 'Quote', name: 'content', widget: 'string', required: true, hint: "Don't add in quotes. They get added automatically." }
      - label: "Slideshow"
        name: "slides"
        widget: "list"
        hint: "Add images with optional captions to be displayed in a slideshow"
        fields:
          - { label: 'Caption', name: 'title', widget: 'string', required: false }
          - label: "Image"
            name: "image"
            widget: "image"
            hint: 'Upload an image at least 1000px wide'
            media_library:
              name: cloudinary
              config:
                multiple: false
                default_transformations:
                  - - width: 1000
                      crop: fit
      - label: "Audio"
        name: "audio"
        widget: "list"
        hint: "Upload clips of audio to showcase"
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'text', required: false }
          - label: "Audio Link"
            name: "link"
            widget: "file"
            media_library:
              name: '/audio'
              config:
                multiple: false
  - name: 'writing'
    create: true
    label: 'Writing Page'
    editor:
        preview: false
    folder: '_writing/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'writing' }
      - { label: 'Title', name: 'title', widget: 'string', required: true  }
      - { label: 'Sorting Date', name: 'date', widget: 'datetime', hint: 'The date used for sorting. Leave set to Now to display as most recent' }
      - { label: 'Publication Date', name: 'time', widget: 'string', hint: 'The displayed date for the article e.g. Apr 2020' }
      - { label: 'Excerpt ', name: 'excerpt', widget: 'text', required: true, hint: 'The article excerpt to be displayed. Try to keep it short and sweet.' }
      - { label: 'Publication', name: 'publication', widget: 'string', required: true, hint: 'Where the article was published e.g. Silicon Republic'  }
      - { label: 'URL', name: 'link', widget: 'string', required: true, hint: 'The URL to the article'  }
      - label: "Featured Image"
        name: "image"
        widget: "image"
        hint: 'Upload an image at least 1100px wide and 640px tall'
        media_library:
          name: cloudinary
          config:
            multiple: false
            default_transformations:
              - - width: 1100
                  height: 640
  - name: 'about_page'
    label: 'About Page'
    editor:
      preview: false
    files:
      - label: 'Content'
        name: 'about_content'
        file: 'about.html'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Page Title', name: 'title', widget: 'string', default: 'About me' }
          - { label: 'Page Description', name: 'description', widget: 'string' }
          - { label: 'Callout Title', name: 'callout_title', widget: 'string', default: 'Did you know?' }
          - { label: 'Callout Description', name: 'callout_description', widget: 'string', default: 'Been there, wrote a book on being a woman in STEM' }
          - { label: 'Callout Link', name: 'callout_link', widget: 'string', default: 'https://www.amazon.co.uk/Uncovering-Truffles-Scarcity-Value-Women/dp/1515304280/ref=sr_1_1?keywords=uncovering+truffles&qid=1585251895&sr=8-1' }
      - label: 'Section 1'
        name: 'section_1'
        file: 'about-section-1.md'
        fields:
          - { label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Section 2'
        name: 'section_2'
        file: 'about-section-2.md'
        fields:
          - { label: 'Content', name: 'body', widget: 'markdown'}
  - name: 'coaching_page'
    label: 'Coaching Page'
    editor:
      preview: false
    files:
      - label: 'Content'
        name: 'coaching_content'
        file: 'coaching.html'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Page Title', name: 'title', widget: 'string', default: 'Coaching' }
          - { label: 'Page Description', name: 'description', widget: 'string', default: 'ICF-certified professional career, life & executive coach.' }
          - { label: 'Callout 1 Title', name: 'callout_1_title', widget: 'string', default: 'Download my free coaching packet' }
          - { label: 'Callout 1 Description', name: 'callout_1_description', widget: 'string', default: 'Download my introductory coaching packet to learn more about what I can do for you.' }
          - { label: 'Callout 1 Link', name: 'callout_1_link', widget: 'string' }
          - { label: 'Callout 2 Title', name: 'callout_2_title', widget: 'string', default: 'Get a free 30-minute coaching session' }
          - { label: 'Callout 2 Description', name: 'callout_2_description', widget: 'string', default: "It’s a low-risk way to learn more about coaching and get a taste of my coaching style." }
          - { label: 'Callout 2 Link', name: 'callout_2_link', widget: 'string', default: 'mailto:melanie@melaniepolkosky.com?subject=I%20would%20like%20a%20free%2030-minute%20coaching%20session' }
      - label: 'Section 1'
        name: 'section_1'
        file: 'coaching-section-1.md'
        fields:
          - { label: 'Content', name: 'body', widget: 'markdown'}
  - label: 'Coaching Testimonials'
    name: 'testimonails'
    folder: '_testimonials/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true, hint: "E.g. Product designer"  }
      - { label: 'job', name: 'job', widget: 'string', required: true, hint: "The Company or job sector. E.g. Square"  }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
      - { label: 'Type', name: 'type', widget: 'select', required: true, options: ["Coaching", "Mentoring"] }
      - label: "Featured Image"
        name: "image"
        widget: "image"
        hint: 'Image will be cropped to 480px by 600px'
        media_library:
          name: cloudinary
          config:
            multiple: false
            default_transformations:
              - - width: 480
                  height: 600
  - name: 'agreement_page'
    label: 'Coaching Agreement Page'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'coaching-agreement' }
      - { label: 'Page Title', name: 'title', widget: 'string', default: 'Coaching Agreement' }
      - { label: 'Page Description', name: 'description', widget: 'string', default: 'Just one final step.' }
      # - label: "Content Section"
      #   name: "accordion"
      #   widget: "list"
      #   fields:
      #     - { label: 'Title', name: 'title', widget: 'string', required: true }
      #     - { label: 'Content', name: 'content', widget: 'string', required: true }
      #     - label: "List"
      #       widget: "list"
      #       fields:
      #         - { label: 'Content', name: 'content', widget: 'markdown', required: true }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home Page'
        name: 'index'
        file: 'index.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'home' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'index' }
          - { label: 'Page Title', name: 'subtitle', widget: 'string' }
          - { label: 'Page Description', name: 'description', widget: 'string' }
          - { label: 'Column 1', name: 'intro_column_1', widget: 'text', required: true }
          - { label: 'Column 2', name: 'intro_column_2', widget: 'text', required: true }
          - label: "Timeline Section"
            name: "timeline"
            widget: "list"
            fields:
              - { label: 'Date', name: 'timeline_item_date', widget: 'string', required: true }
              - { label: 'Title', name: 'timeline_item_title', widget: 'string', required: true }
              - { label: 'Quote', name: 'timeline_item_quote', widget: 'string', required: true }
          - label: "Links Section"
            name: "talks_interviews"
            widget: "list"
            fields:
              - { label: 'Publication', name: 'title', widget: 'string', required: true, hint: "e.g. Silicon Republic" }
              - { label: 'Title', name: 'description', widget: 'string', required: true, hint: "e.g. Career Profile in Silicon Republic" }
              - { label: 'URL', name: 'link', widget: 'string', required: true }
              - { label: 'Date', name: 'date', widget: 'string', required: true, hint: "e.g. Apr 2020" }
          - label: "Social Section"
            name: "social"
            widget: "list"
            fields:
              - { label: 'Name', name: 'name', widget: 'string', required: true }
              - { label: 'Link', name: 'link', widget: 'string', required: true }

      - label: 'About Page'
        name: 'about'
        file: 'about.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Page Description', name: 'description', widget: 'string' }
          - { label: 'Animation', name: 'animation', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
