# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/'
site_url: melaniepolkosky.com

collections:
  - name: 'portfolio'
    identifier_field: thumbnail_title
    editor:
        preview: false
    label: 'Portfolio Page'
    slug: '{{slug}}'
    folder: '_portfolio/'
    create: true
    fields:
      - { label: 'Title', name: 'thumbnail_title', widget: 'string', required: true,  }
      - { label: 'Page Title', name: 'title', widget: 'string', required: true,  }
      - { label: 'Category', name: 'category', widget: 'select', required: true, options: ['Strategy Consulting', 'Training', 'UI Design', 'UX Research'] }
      - { label: 'Role', name: 'role', widget: 'string', required: false }
      - { label: 'Company', name: 'company', widget: 'string', required: false }
      - { label: 'Client', name: 'client', widget: 'string', required: false }
      - { label: 'Time', name: 'time', widget: 'string', required: false }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'portfolio-single' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      # - label: "Details"
      #   name: "details"
      #   widget: "object"
      #   fields:
      #     - { label: 'Role', name: 'role', widget: 'string', required: false }
      #     - { label: 'Company', name: 'company', widget: 'string', required: false }
      #     - { label: 'Client', name: 'client', widget: 'string', required: false }
      #     - { label: 'Time', name: 'time', widget: 'string', required: false }
  - name: 'writing'
    extension: yml
    create: true
    slug: '{{slug}}'
    label: 'Writing Page'
    folder: '_writing/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'writing' }
      - { label: 'Title', name: 'title', widget: 'string', required: true  }
      - { label: 'URL', name: 'url', widget: 'string', required: true  }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: true }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home Page'
          name: 'home'
          file: 'home.html'
          fields:
            - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
            - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
            - { label: 'Page Title', name: 'title', widget: 'string' }
            - { label: 'Page Description', name: 'description', widget: 'string' }
            - { label: 'Body', name: 'body', widget: 'code' }
      - label: 'About Page'
        name: 'about'
        file: 'about.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Page Title', name: 'title', widget: 'string' }
          - { label: 'Page Description', name: 'description', widget: 'string' }
          - { label: 'Animation', name: 'animation', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'code' }
