# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/'

collections:
  - name: 'portfolio'
    editor:
        preview: false
    label: 'Portfolio'
    slug: '{{slug}}'
    folder: '_portfolio/'
    fields:
      - { label: 'Title', name: 'thumbnail_title', widget: 'string', required: true,  }
      - { label: 'Page Title', name: 'title', widget: 'string', required: true,  }
      - { label: 'Category', name: 'category', widget: 'select', required: true, options: ['Strategy Consulting', 'training', 'UI Design', 'UX Research', ''] }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'portfolio-single' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    - label: "Details"
      name: "details"
      widget: "object"
      fields:
        - { label: 'Role', name: 'role', widget: 'string' }
        - { label: 'Company', name: 'company', widget: 'string' }
        - { label: 'Client', name: 'client', widget: 'string' }
        - { label: 'Time', name: 'time', widget: 'string' }
    create: true
  - name: 'writing'
    label: 'writing'
    folder: '_writing/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { name: Title }
