# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/'

collections:
  - name: 'portfolio'
    label: 'Portfolio'
    folder: '_portfolio/'
    fields:
      - { name: Title }
  - name: 'writing'
    label: 'writing'
    folder: '_writing/'
    fields:
      - { name: Title }